packages:
  - 'packages/*'
  - 'apps/*'

shamefullyHoist: true
autoInstallPeers: true
strictPeerDependencies: false

allowBuilds:
  '@google/genai': true
  '@vscode/vsce-sign': true
  electron-winstaller: true
  esbuild: true
  protobufjs: true

minimumReleaseAgeExclude:
  - vite@8.3.1
  - lucide-react@1.48.0

overrides:
  '@electron/asar': ^4.3.0
  '@electron/universal': ^3.0.6
  '@electron/get': ^5.1.0
  rimraf: ^5.0.10
  glob: ^13.0.6
